In [46]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [56]:
df1 = pd.read_csv('spam.csv',encoding='latin#1')

In [50]:
df1

Document  Class
0         Teclov is a great educational institution.    1.0
1            Educational greatness depends on ethics    1.0
2  A story of great ethics and educational greatness    1.0
3                           Sholey is a great cinema    NaN
4                   good movie depends on good story    NaN

In [75]:
df1['v1'] = df1.v2.map({'ham':0, 'spam':1})
df1

v1                                                 v2 Unnamed: 2  \
0    NaN  Go until jurong point, crazy.. Available only ...        NaN   
1    NaN                      Ok lar... Joking wif u oni...        NaN   
2    NaN  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3    NaN  U dun say so early hor... U c already then say...        NaN   
4    NaN  Nah I don't think he goes to usf, he lives aro...        NaN   
...   ..                                                ...        ...   
5567 NaN  This is the 2nd time we have tried 2 contact u...        NaN   
5568 NaN              Will Ì_ b going to esplanade fr home?        NaN   
5569 NaN  Pity, * was in mood for that. So...any other s...        NaN   
5570 NaN  The guy did some bitching but I acted like i'd...        NaN   
5571 NaN                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  Class  
0           NaN        NaN    NaN  
1           NaN        NaN    NaN  
2           NaN        NaN    NaN  
3           NaN        NaN    NaN  
4           NaN        NaN    NaN  
...         ...        ...    ...  
5567        NaN        NaN    NaN  
5568        NaN        NaN    NaN  
5569        NaN        NaN    NaN  
5570        NaN        NaN    NaN  
5571        NaN        NaN    NaN  

[5572 rows x 6 columns]

In [76]:
X= df1['v2'].to_numpy()
Y = df1['v1'].to_numpy()
Y = Y.astype('int')

In [77]:
print("X")
print(X)
print("Y")
print(Y)

X
['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 ... 'Pity, * was in mood for that. So...any other suggestions?'
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name']
Y
[-9223372036854775808 -9223372036854775808 -9223372036854775808 ...
 -9223372036854775808 -9223372036854775808 -9223372036854775808]


In [78]:
vec = CountVectorizer( )

In [80]:
vec = CountVectorizer(stop_words='english' )
vec.fit(X)
vec.vocabulary_

{'jurong': 4224,
 'point': 5741,
 'crazy': 2271,
 'available': 1271,
 'bugis': 1703,
 'great': 3534,
 'world': 8227,
 'la': 4349,
 'buffet': 1701,
 'cine': 1994,
 'got': 3494,
 'amore': 1051,
 'wat': 8026,
 'ok': 5343,
 'lar': 4385,
 'joking': 4192,
 'wif': 8134,
 'oni': 5369,
 'free': 3265,
 'entry': 2875,
 'wkly': 8185,
 'comp': 2110,
 'win': 8146,
 'fa': 3005,
 'cup': 2329,
 'final': 3121,
 'tkts': 7519,
 '21st': 411,
 '2005': 402,
 'text': 7388,
 '87121': 784,
 'receive': 6115,
 'question': 6010,
 'std': 7028,
 'txt': 7701,
 'rate': 6062,
 'apply': 1128,
 '08452810075over18': 77,
 'dun': 2738,
 'say': 6450,
 'early': 2757,
 'hor': 3815,
 'nah': 5092,
 'don': 2651,
 'think': 7443,
 'goes': 3458,
 'usf': 7837,
 'lives': 4535,
 'freemsg': 3272,
 'hey': 3732,
 'darling': 2386,
 'week': 8071,
 'word': 8218,
 'like': 4485,
 'fun': 3323,
 'tb': 7323,
 'xxx': 8292,
 'chgs': 1948,
 'send': 6536,
 '50': 607,
 'rcv': 6074,
 'brother': 1674,
 'speak': 6910,
 'treat': 7634,
 'aids': 985,
 'pate

In [81]:
vec = CountVectorizer(stop_words='english' )
vec.fit(X)
vec.vocabulary_

{'jurong': 4224,
 'point': 5741,
 'crazy': 2271,
 'available': 1271,
 'bugis': 1703,
 'great': 3534,
 'world': 8227,
 'la': 4349,
 'buffet': 1701,
 'cine': 1994,
 'got': 3494,
 'amore': 1051,
 'wat': 8026,
 'ok': 5343,
 'lar': 4385,
 'joking': 4192,
 'wif': 8134,
 'oni': 5369,
 'free': 3265,
 'entry': 2875,
 'wkly': 8185,
 'comp': 2110,
 'win': 8146,
 'fa': 3005,
 'cup': 2329,
 'final': 3121,
 'tkts': 7519,
 '21st': 411,
 '2005': 402,
 'text': 7388,
 '87121': 784,
 'receive': 6115,
 'question': 6010,
 'std': 7028,
 'txt': 7701,
 'rate': 6062,
 'apply': 1128,
 '08452810075over18': 77,
 'dun': 2738,
 'say': 6450,
 'early': 2757,
 'hor': 3815,
 'nah': 5092,
 'don': 2651,
 'think': 7443,
 'goes': 3458,
 'usf': 7837,
 'lives': 4535,
 'freemsg': 3272,
 'hey': 3732,
 'darling': 2386,
 'week': 8071,
 'word': 8218,
 'like': 4485,
 'fun': 3323,
 'tb': 7323,
 'xxx': 8292,
 'chgs': 1948,
 'send': 6536,
 '50': 607,
 'rcv': 6074,
 'brother': 1674,
 'speak': 6910,
 'treat': 7634,
 'aids': 985,
 'pate

In [89]:
print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['00' '000' '000pes' ... 'ûïharry' 'ûò' 'ûówell']
8404


In [96]:
#X_transformed=vec.transform(X)
#X_transformed
X_transformed = vec.transform([str(x) for x in X])

In [97]:
X=X_transformed.toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [98]:
pd.DataFrame(X, columns=vec.get_feature_names_out())

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0      0    0       0             0     0     0            0            0   
1      0    0       0             0     0     0            0            0   
2      0    0       0             0     0     0            0            0   
3      0    0       0             0     0     0            0            0   
4      0    0       0             0     0     0            0            0   
...   ..  ...     ...           ...   ...   ...          ...          ...   
5567   0    0       0             0     0     0            0            0   
5568   0    0       0             0     0     0            0            0   
5569   0    0       0             0     0     0            0            0   
5570   0    0       0             0     0     0            0            0   
5571   0    0       0             0     0     0            0            0   

      0125698789  02  ...  ó_  û_  û_thanks  ûªm  ûªt  ûªve  ûï  ûïharry  ûò  \
0              0   0  ...   0   0         0    0    0     0   0        0   0   
1              0   0  ...   0   0         0    0    0     0   0        0   0   
2              0   0  ...   0   0         0    0    0     0   0        0   0   
3              0   0  ...   0   0         0    0    0     0   0        0   0   
4              0   0  ...   0   0         0    0    0     0   0        0   0   
...          ...  ..  ...  ..  ..       ...  ...  ...   ...  ..      ...  ..   
5567           0   0  ...   0   0         0    0    0     0   0        0   0   
5568           0   0  ...   0   0         0    0    0     0   0        0   0   
5569           0   0  ...   0   0         0    0    0     0   0        0   0   
5570           0   0  ...   0   0         0    0    0     0   0        0   0   
5571           0   0  ...   0   0         0    0    0     0   0        0   0   

      ûówell  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
5567       0  
5568       0  
5569       0  
5570       0  
5571       0  

[5572 rows x 8404 columns]

In [100]:
df2 = pd.read_csv('spam.csv',encoding='latin#1')
df2

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [102]:
#test_numpy_array = df2.values
#X_test = test_numpy_array[:, 0]
#y_test = test_numpy_array[:, 1]
#y_test = y_test.astype('int')
#print("X_test:", X_test)
#print("y_test:", y_test)
unique_values = np.unique(y_test)
print(unique_values)

[' &lt;#&gt;  in mca. But not conform.'
 ' &lt;#&gt;  mins but i had to stop somewhere first.'
 ' &lt;DECIMAL&gt; m but its not a common car here so its better to buy from china or asia. Or if i find it less expensive. I.ll holla'
 ... 'ÌÏ thk of wat to eat tonight.' 'ÌÏ v ma fan...'
 'ÌÏ wait 4 me in sch i finish ard 5..']


In [103]:
X_test_transformed=vec.transform(X_test)
X_test_transformed

<5572x8404 sparse matrix of type '<class 'numpy.int64'>'
	with 5572 stored elements in Compressed Sparse Row format>

In [104]:
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [105]:
mnb=MultinomialNB()

mnb.fit(X,Y)

mnb.predict_proba(X_test)

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [107]:
y_prediction = mnb.predict(X_test)


acc = accuracy_score(y_test, y_prediction)


print("Accuracy:", acc)


Accuracy: 0.0
